name: C# CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - name: Generate binaries
      run: |
        dotnet restore /p:Configuration=Debug /p:Platform="Any CPU"
        MSBuild.exe TCGPocketAutomation.csproj /p:Configuration=Debug
    - uses: actions/upload-artifact@v4
      with:
        name: TCGPocketAutomation for windows
        path: bin/Debug/net8.0-windows